EliasOenal/multimon-ng

BCHCode.c, BCHCode.h, CMakeLists.txt, README.md, demod_flex.c, multimon-ng.pro, multimon.h
Support for FLEX paging protocol, ported from GNURadio with addition of slicer and phase locking algorithm. This supports 2 level and 4 level encoding, and has been tested at 1600 symbols per second. 3200 symbols per second is supported, however it has not been tested.
Error correction is provided by the BCHCode class, which is used with the same generator polynomial coefficients as is used in POCSAG. Plain text decodes of the paging messages are date/time stamped and written to the standard output. Further debug messages are available, with debug level 3 being the most useful for studying the performance of this demodulator.
=> Add Support for FLEX Paging Protocol

CMakeLists.txt, demod_flex.c
The current FLEX implementation used longs, and it seems it was only tested on a 64-bit target originally. This PR contains fixes for this, and tries to patch up use of unsigned long and unsigned long long (which is just aesthetic at this point) as c99 stdint types.
Tested on an x86_64 host and an ARMv7 host, and no regressions were found.
=> Fix FLEX pager demodulation on 32-bit targets

demod_flex.c
Minor type cleanups for AArch64. Removes some type ambiguity, and fixes a busted printf formatting string. Also make a minor tweak to the range of valid CAPCODEs, per the FLEX specification.
This has been tested on AArch64, armv7 and x86_64.
=> FLEX: Fix type errors on aarch64

fms.c
Due to changes in local TR (RLP) there are hex-values allowed in the vehicle-id-field.
This change has no effect to existing installations as it only increases the number of available ids.
=> Adapting vehicle-id from dec to hex

unixinput.c
I am using this to add a label to the output when decoding multiple channels.
=> Add --label / -l which prefixes lines with text

demod_x10.c
Fixes the following warnings:
* -Wdiscarded-qualifiers
* -Wunused-variable
* -Wunused-but-set-variable
=> x10: fix various compiler warnings

demod_x10.c
Comment out both the above includes as they cause compile errors on Windows, does not seem to cause any issues running the program afterwards, issue #96
=> Comment out includes for sys/wait and sys/resource

xdisplay.c
XNextEvent blocks while no events are available. The first time
the child display process enters process_keystrokes(), it loops
forever inside x_getkey() and never gets to update the display.
This changes XNextEvent to XCheckWindowEvent, which does
not block.
=> Fix event polling loop in SCOPE demodulator

win32_getopt.c, win32_getopt.h
This restores the FSF copyright notice that had disappeared from this port of getopt. All changes done for the port could easily be done by machine, so the FSF likely holds the sole copyright on these files. Please consider merging.
=> Restore FSF copyright notices on win32_getopt.[ch]

demod_flex.c
Here are the results of my investigation into restoring the FSF copyright notice on demod_flex.c, as mentioned in #108. Please have a look to see if it makes sense.
=> Restore FSF notice on the FLEX decoder derived from GNU Radio

demod_flex.c
My local pager service (SA GRN) did a major upgrade recently that exposed a logic flaw in the way messages where being identified as complete or fragmented.
This fix only affects the 'K', 'C' and 'F' information embedded in the output.  Any external code that reads them and acts on them (to join fragmented messages) should be checked if you deploy this fix.
K,C,F explained:
'K' = complete message, ready to send.
'C' = incomplete message   (a fragment). Buffer until appended to 1 or more 'F's.
'F' = incomplete message  (a fragment). Buffer until a 'C' fragment is appended.
The old logic incorrectly tagged some 'C' fragments as 'K', meaning you'd probably have chosen to join miss-tagged 'K' fragment onto any buffered 'F' fragments.  Testing suggests that with the new logic, any 'K' message …
=> Flex fragment fix

unixinput.c
=> Set stdin to binary mode to fix piping on Windows

demod_dtmf.c
During some testing I found out that (with my setup) non DTMF sounds (general city sound, car traffic, police siren, women screaming, ...) could trigger the detection. After some investigation I found out that  the difference between a valid and invalid detection could be simply made.
The enhancement I made is to check if the energy levels of the 2 detected frequencies is about the same (in a 300% range).
A DTMF is generated with 2 frequencies of the same energy level. So that is also what should be detected. 
In the non DTMF sound I used, most of the detection where of 2 frequencies that were in the range of 50000%.
=> filter false positive DTMF detections

multimon.h, pocsag.c, unixinput.c
POCSAG tells you whether a msg is numeric or alphanumeric with the function code (0=num, 3=alpha)
The only decision to make is if an alpha msg is plain or skyper!, but we don't want to penalise NUL characters (some systems pad with NUL!)
It's not an exact science yet, but it does a slightly better job now!
=> Compare function codes and don't penalise NUL

pocsag.c
Using the German charset, I replaced Ü with Å so it displays correctly with Swedish charset. I also changed the uncoded UE to AO and removed the SS.
=> Added Swedish charset

fms.c, unixinput.c
Added option to just output the fms hex data. Many programs are parsing stdout from multimon-ng. Depending on application, leaving out the additional info increases performance and makes parsing easier.
=> Added option to output FMSFSK packets just as hex and crc

unixinput.c
Automatic reproducibility tests in Debian found that the multimon-ng binary contained the filename of the directory it was built in. Please accept this small change to make the binary reproducible.
=> Remove the use of __FILE__ to fix build reproducibility

pocsag.c
Added missing characters used in Slovenian character set for POCSAG.
=> Character set SI: Added missing characters

.github/workflows/ccpp.yml, .gitignore, demod_flex.c
Fixes #139 adds edges cases for start and end offsets to avoid missing start characters in FLEX messages.
Also include some changes that:
* remove compiler warnings/type ambiguity when on Raspberry Pi architecture
* refactors mw1 and len calculations into single place
* centralize hardcoded sizes and offsets
* handle long vs short address and single vs group decoding, particular as it pertains to:
* changing the start and end offset of message content
* decoding the capcode
* decode the frag bit
* refactors the message printing to encode printable whitespace modifiers so messages are printing on a single line, avoid empty messages, filter non-printables, convert % into literal (%%).
=> 139 characters missing from flex

pocsag.c
While working on #179 I noticed some bugs in the print-message related code.
- **Fix `guesstimate_*()` usage**
unsigned int was used to store/pass possibly negative numbers
- **Combine print_msg_alpha and print_msg_skyper**
functions should be virtually identical, but bugs have crept into the skyper version. combining them removes the possibility of further diverging
apologies for a seperate pull request right after the other, i forgot to publish this one. (it does depend on the previous, and extending it didn't feel right to me anyways)
=> Pocsag bugfix and cleanup (Follow-up to #179)

unixinput.c
When multimon-ng reads a WAV file it uses SoX to convert it to raw
samples. If that data is streamed via a pipe then the WAV header will
not contain the right length, so SoX will terminate early.
This adds --ignore-length to SoX's argument list, which will make it
read until the end of the input file.
Closes: #194
=> Pass --ignore-length to SoX to support piped WAV data

demod_flex.c
Multimon from Debian crashed when decoding pager flex data, with an error message about %n printf vulnerabilities.  I found that a verbprintf call in demod_flex.c had only two params, so the pager payload was being sent as a format string.
I confirmed that a pager text had contained the characters "%n", which caused the crash. 
The fix is to just add %s, which treats the data as a string, rather than a format.  After the fix, I replayed the data, and no crash happened.
https://cs155.stanford.edu/papers/formatstring-1.2.pdf
=> Bug / security fix: printf format string uses received data

demod_flex_next.c
The message contents were trusted as a format argument, resulting in a potential format string bug. This commit fixes the issue.
=> demod_flex_next.c: parse_alphanumeric: Fix format string bug

demod_afsk12.c, demod_poc12.c, demod_poc5.c
Fixed POCSAG512 and POCSAG1200 decoders not working when fed small amounts of data (e.g. pipes, etc). This should fix issues #213, #197, #91, #70.
The same problem may be present in some other decoders. I have not checked. Please, do.
=> Fixing POCSAG decoders not working when fed small data over pipes, etc.

demod_afsk12.c, demod_clipfsk.c, demod_eas.c, demod_fmsfsk.c, demod_ufsk12.c
These changes fix the subsampling algorithm in the remaining decoders which had the previous, broken algorithm. Please note that **I have no way to test these decoders**. If you have any sample input, you probably want to test the new code on that input.
=> Fixed subsampling in AFSK12, CLIPFSK, EAS, FMSFSK, UFSK12 decoders

demod_flex.c, unixinput.c
Suppress timestamp by passing the argument `--flex-no-ts`
1. Many users incorrectly assume the timestamp originates from the FLEX message but its the system time. The value is useless when for example passing a recording.
2. Suppressing the timestamp makes it easier to compare output of this and future versions based on the same input file.
Default:
```
FLEX|2024-09-12 16:37:13|1600/2/K/A|03.011|002029575 000120111 000120999|ALN|A2 13111 Tweede Oosterparkstraat 1092 Amsterdam 82536
```
With  `--flex-no-ts`
```
FLEX|1600/2/K/A|03.011|002029575 000120111 000120999|ALN|A2 13111 Tweede Oosterparkstraat 1092 Amsterdam 82536
```
With  `--flex-no-ts --timestamp`
```
2024-09-12 18:40:16: FLEX|1600/2/K/A|03.011|002029575 000120111 000120999|ALN|A2 13111 Tweede Oosterparkstraat 1092 Amsterdam 82536 …
```
=> FLEX: Suppress timestamp by passing `--flex-no-ts`

CMakeLists.txt, unixinput.c
Adds an `--iso-8601` argument so that timestamps are UTC based and include microseconds. This is especially useful when:
1. passing data between systems
2. Timestamps aren't affected by Daylight Saving Time changes
3. A lot can happen in a second and makes it easier to filter/correlate log entries with other components
Output example:
```
2024-09-13T21:57:39.154618: FLEX|2024-09-13 21:57:39|1600/2/K/A|03.011|002029575 000120111 000120999|ALN|A2 13111 Tweede Oosterparkstraat 1092 Amsterdam 82536
```
=> Timestamp UTC ISO-8601 mode

demod_flex.c
When using `--timestamp` the prefix was only added to the first FLEX outputted message.
Fix where \n was not passed to `verbprintf` thus not detected resulting in its new line detection to fail and no timestamp prefix to appear until an `verbprintf` invocation happened that did trigger the new line if branch.
Before:
```
2024-09-15T18:24:05.392795: FLEX|1600/2/K/A|06.012|002029572 001403003 001403590|ALN|P 2 BRT-02 Liftopsluiting Johan de Wittstraat Dordrecht 186531
FLEX|1600/2/K/A|06.031|002029578 001420059 001420999|ALN|A0 AMBU 17992 Bekestein 3343CB Hendrik-Ido-Ambacht HENDIA bon 130990
FLEX|1600/2/K/A|06.040|002029568 001002747 001002750 001002873 001002880 001005998 001033002|ALN|P 2 BLB-01 Bodemverontreiniging Newtonweg Venlo 233291 236121
```
After:
```
2024-09-15T18:24:05.392795: …
```
=> FLEX: Fix edge case where no timestamp prefix was added when running with `--timestamp`

CMakeLists.txt, cJSON.c, cJSON.h, demod_dtmf.c, demod_eas.c, demod_flex.c, multimon-ng.pro, multimon.h, pocsag.c, unixinput.c
As per my comments in #190 this is a minimally-working attempt.
Again, I'm not a C programmer these days, and it might be rough.  Hoping the devs or others can chip in and help out.
=> Add JSON (partial)
